# Site settings
author: Nikolaus Riggi
title: Just An Algorithm Away
header-img: img/home-bg.png
email: nikolaus.riggi@gmail.com
copyright_name: Nikolaus Riggi
description: > # this means to ignore newlines until "baseurl:"
  Lets learn some code 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FreeRunner34

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
