# Site settings
author: Nikolaus Dean Riggi
title: 
header-img: img/home-bg.png
email: nikolaus.riggi@gmail.com
copyright_name: Nikolaus Dean Riggi
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FreeRunner34

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
